version: '3.9'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=567234
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    web:
        build: .
        ports:
           - 8000:8000
        environment:
            - DJANGO_SUPERUSER_USERNAME=admin
            - DJANGO_SUPERUSER_EMAIL=admin@admin.com
            - DJANGO_SUPERUSER_PASSWORD=admin
        command: bash -c 
            "python manage.py migrate 
            && python manage.py createsuperuser --noinput 
            && python -m utils.migration 
            && python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - db

volumes:
  postgres_data: